import { Card, Badge } from "@/components/ui";
import TrendingBarChart from "./TrendingBarChart";
import ColumnChart from "./ColumnChart";

// "AI market pulse" — the board's stats + charts section, powered by Gemini
// ESTIMATES (see generateMarketInsights), refreshed weekly and cached. Every
// piece is labeled as an estimate: these are not measurements from this board.
// Server component: receives the cached payload as plain data.
export default function AiMarketPulse({
  insights,
  generatedAt,
  stale = false,
}) {
  if (!insights?.demand?.length) return null;

  const demand = [...insights.demand]
    .sort((a, b) => b.score - a.score)
    .map((d) => ({ name: d.category, score: d.score }));
  const highlights = insights.highlights ?? [];
  const trend = insights.trend ?? [];
  const updated = generatedAt
    ? new Date(generatedAt).toLocaleDateString("en-IN", {
        day: "numeric",
        month: "short",
      })
    : null;

  return (
    <div>
      <div className="mb-3 flex flex-wrap items-center gap-2">
        <i className="uil uil-robot text-accent" />
        <h2 className="text-sm font-semibold tracking-wide uppercase text-body">
          AI market pulse
        </h2>
        <Badge>AI estimates · weekly</Badge>
      </div>

      {highlights.length > 0 && (
        <div className="mb-3 grid grid-cols-2 gap-3 sm:grid-cols-4">
          {highlights.map((h) => (
            <div
              key={h.label}
              className="rounded-lg border border-solid border-line/70 bg-surface px-4 py-3"
              title={h.note}
            >
              <div
                className="truncate text-lg font-bold text-title"
                title={h.value}
              >
                {h.value}
              </div>
              <div className="text-xs text-body-light">{h.label}</div>
              {h.note && (
                <div className="mt-1 line-clamp-2 text-[11px] leading-snug text-body-light/80">
                  {h.note}
                </div>
              )}
            </div>
          ))}
        </div>
      )}

      <div className="grid gap-3 lg:grid-cols-2">
        <Card>
          <h3 className="mb-2 text-sm font-semibold text-title">
            <i className="uil uil-chart-bar text-accent" /> Buying interest by
            category
            <span className="ml-2 text-xs font-normal text-body-light">
              0–100, AI estimate
            </span>
          </h3>
          <TrendingBarChart
            data={demand}
            valueKey="score"
            valueLabel="Interest"
          />
        </Card>
        {trend.length > 0 && (
          <Card>
            <h3 className="mb-2 text-sm font-semibold text-title">
              <i className="uil uil-chart-growth text-accent" /> Buying
              interest, last 6 months
              <span className="ml-2 text-xs font-normal text-body-light">
                index, AI estimate
              </span>
            </h3>
            <ColumnChart
              data={trend}
              xKey="month"
              yKey="index"
              label="Interest index"
              className="h-82"
            />
          </Card>
        )}
      </div>

      <p className="mt-2 text-[11px] text-body-light">
        Estimates generated by AI from general market knowledge — not
        measurements from this board{updated ? ` · updated ${updated}` : ""}
        {stale ? " · refresh pending, showing the latest saved data" : ""}.
      </p>
    </div>
  );
}
