import { Card, Badge } from "@/components/ui";
import TrendingBarChart from "./TrendingBarChart";
import ColumnChart from "./ColumnChart";

// "AI market pulse" — the board's stats + charts section, powered by Gemini
// ESTIMATES (see generateMarketInsights), refreshed weekly and cached. Every
// piece is labeled as an estimate: these are not measurements from this board.
// Server component: receives the cached payload as plain data.
export default function AiMarketPulse({
  insights,
  generatedAt,
  stale = false,
  hues = {},
}) {
  if (!insights?.demand?.length) return null;

  const demand = [...insights.demand]
    .sort((a, b) => b.score - a.score)
    .map((d) => ({ name: d.category, score: d.score }));
  const highlights = insights.highlights ?? [];
  const trend = insights.trend ?? [];
  const updated = generatedAt
    ? new Date(generatedAt).toLocaleDateString("en-IN", {
        day: "numeric",
        month: "short",
      })
    : null;

  return (
    <div>
      <div className="mb-3 flex flex-wrap items-center gap-2">
        <i className="uil uil-robot text-accent" />
        <h2 className="text-sm font-semibold tracking-wide uppercase text-body">
          AI market pulse
        </h2>
        <Badge>AI estimates · weekly</Badge>
      </div>

      {/* one tile per admin-managed category — grows with the category list,
          so it scrolls horizontally like the trending strips */}
      {highlights.length > 0 && (
        <div className="-mx-1 mb-3 flex gap-3 overflow-x-auto px-1 pb-2">
          {highlights.map((h) => {
            const hue = hues[h.category] ?? 210;
            return (
              <div
                key={h.category ?? h.label}
                className="flex w-52 shrink-0 flex-col overflow-hidden rounded-lg border border-solid border-line/70 bg-surface"
                title={h.note}
              >
                <div
                  className="flex items-center gap-1.5 px-4 pt-3 text-xs font-medium text-body-light"
                  style={{
                    background: `linear-gradient(180deg, hsl(${hue} 70% 50% / 0.18), transparent)`,
                  }}
                >
                  <span
                    className="inline-block h-2 w-2 rounded-full"
                    style={{ background: `hsl(${hue} 70% 50%)` }}
                  />
                  {h.category ?? "Market"}
                </div>
                <div className="px-4 pb-3">
                  <div
                    className="truncate text-lg font-bold text-title"
                    title={h.value}
                  >
                    {h.value}
                  </div>
                  <div className="text-xs font-medium text-body">{h.label}</div>
                  {h.note && (
                    <p className="mt-1 line-clamp-2 text-[11px] leading-snug text-body-light">
                      {h.note}
                    </p>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      )}

      <div className="grid gap-3 lg:grid-cols-2">
        <Card>
          <h3 className="mb-2 text-sm font-semibold text-title">
            <i className="uil uil-chart-bar text-accent" /> Buying interest by
            category
            <span className="ml-2 text-xs font-normal text-body-light">
              0–100, AI estimate
            </span>
          </h3>
          <TrendingBarChart
            data={demand}
            valueKey="score"
            valueLabel="Interest"
          />
        </Card>
        {trend.length > 0 && (
          // same height as the category card (grid stretch); the chart is a
          // flex child that grows to fill whatever height that gives it
          <Card className="flex flex-col">
            <h3 className="mb-2 text-sm font-semibold text-title">
              <i className="uil uil-chart-growth text-accent" /> Buying
              interest, last 6 months
              <span className="ml-2 text-xs font-normal text-body-light">
                index, AI estimate
              </span>
            </h3>
            <ColumnChart
              data={trend}
              xKey="month"
              yKey="index"
              label="Interest index"
              className="min-h-52 flex-1"
            />
          </Card>
        )}
      </div>

      <p className="mt-2 text-[11px] text-body-light">
        Estimates generated by AI from general market knowledge — not
        measurements from this board{updated ? ` · updated ${updated}` : ""}
        {stale ? " · refresh pending, showing the latest saved data" : ""}.
      </p>
    </div>
  );
}
