"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Badge, Chip } from "@/components/ui";
import PicksGrid, { PicksSkeleton, shopUrl } from "./PicksGrid";
import { PICK_TOPICS, TOPIC_PICK_COUNT } from "../picks-topics";

const COLS = "grid-cols-2 sm:grid-cols-3 lg:grid-cols-4";

// "Top picks in India" — the board's always-on version of the search
// fallback: tabs of preset topics (trending today / daily-use / high demand),
// 10 AI-picked real products each, every card opening Google Shopping.
// 📘 Client island: tabs are interactive, and each tab lazily fetches its
// list from /api/shop-picks?topic=… (cache-first, refreshed daily server-
// side) the first time it's opened — other tabs cost nothing until clicked.
export default function IndiaPicks({ hues = {} }) {
  const [active, setActive] = useState(PICK_TOPICS[0].key);
  // { [topicKey]: { items, generatedAt, stale } | "failed" } — loaded tabs
  // are kept, no refetch while the page is open
  const [lists, setLists] = useState({});

  useEffect(() => {
    if (lists[active]) return;
    let cancelled = false;
    fetch(`/api/shop-picks?topic=${encodeURIComponent(active)}`)
      .then((res) => (res.ok ? res.json() : { items: null }))
      .then((data) => {
        if (cancelled) return;
        setLists((prev) => ({
          ...prev,
          [active]: data.items?.length
            ? { items: data.items, generatedAt: data.generatedAt, stale: !!data.stale }
            : "failed",
        }));
      })
      .catch(() => {
        if (!cancelled) setLists((prev) => ({ ...prev, [active]: "failed" }));
      });
    return () => {
      cancelled = true;
    };
  }, [active, lists]);

  const topic = PICK_TOPICS.find((t) => t.key === active);
  const current = lists[active];

  // nothing loads (no key / quota / offline) → the whole section steps aside
  const allFailed = PICK_TOPICS.every((t) => lists[t.key] === "failed");
  if (allFailed) return null;

  return (
    <div>
      <div className="mb-3 flex flex-wrap items-center justify-between gap-2">
        <div className="flex flex-wrap items-center gap-2">
          <i className="uil uil-star text-accent" />
          <h2 className="text-sm font-semibold tracking-wide uppercase text-body">
            Top picks in India
          </h2>
          <Badge>AI picks · refreshed daily</Badge>
        </div>
        <a
          href={shopUrl(topic.term)}
          target="_blank"
          rel="nofollow noopener noreferrer"
          className="inline-flex items-center gap-1 rounded-lg border border-solid border-line bg-surface px-3 py-1.5 text-xs font-medium text-title transition-colors hover:border-accent hover:text-accent"
        >
          <i className="uil uil-google" /> See all on Google Shopping
          <i className="uil uil-external-link-alt" />
        </a>
      </div>

      {/* topic tabs — same Chip atom as the category filter */}
      <div
        role="tablist"
        aria-label="Pick topics"
        className="mb-3 flex flex-wrap items-center gap-1.5"
      >
        {PICK_TOPICS.map((t) => (
          <Chip
            key={t.key}
            role="tab"
            aria-selected={t.key === active}
            active={t.key === active}
            onClick={() => setActive(t.key)}
          >
            <i className={`uil ${t.icon} mr-1`} />
            {t.label}
          </Chip>
        ))}
      </div>

      {!current ? (
        <PicksSkeleton
          count={TOPIC_PICK_COUNT}
          cols={COLS}
          label={`Loading ${topic.label.toLowerCase()} picks…`}
        />
      ) : current === "failed" ? (
        <p className="rounded-lg border border-dashed border-line p-4 text-center text-xs text-body-light">
          Couldn&apos;t load this list right now — try another tab.
        </p>
      ) : (
        <PicksGrid items={current.items} hues={hues} cols={COLS} ranked />
      )}

      <p className="mt-2 text-[11px] text-body-light">
        {current && current !== "failed" && current.generatedAt && (
          <>
            <i className="uil uil-clock" /> Updated{" "}
            {new Date(current.generatedAt).toLocaleDateString("en-IN", {
              day: "numeric",
              month: "short",
              timeZone: "Asia/Kolkata",
            })}
            {current.stale && " · today's refresh is pending, showing the latest saved list"}
            {" · "}
          </>
        )}
        Suggestions generated by AI from general market knowledge — prices are
        rough estimates, check the store page. Know a better one?{" "}
        <Link href="/suggest" className="text-accent hover:text-accent-alt">
          Suggest it
        </Link>{" "}
        so it lands on the board.
      </p>
    </div>
  );
}
