"use client";

import { useEffect, useState } from "react";
import { Badge } from "@/components/ui";
import PicksGrid, { PicksSkeleton, shopUrl } from "./PicksGrid";

// Shown ONLY when a text search has zero matches on the board: AI-picked
// real products for the term, each opening Google Shopping. Same client
// pattern as SearchTip: cache-first API, hide on failure.
export default function ShoppingPicks({ term, hues = {} }) {
  const isValid = Boolean(term && term.length >= 2);
  const [items, setItems] = useState(null);
  const [failed, setFailed] = useState(false);
  const [lastTerm, setLastTerm] = useState(term);

  if (lastTerm !== term) {
    setLastTerm(term);
    setItems(null);
    setFailed(false);
  }

  useEffect(() => {
    if (!isValid) return;
    let cancelled = false;
    fetch(`/api/shop-picks?term=${encodeURIComponent(term)}`)
      .then((res) => (res.ok ? res.json() : { items: null }))
      .then((data) => {
        if (cancelled) return;
        if (data.items?.length) setItems(data.items);
        else setFailed(true);
      })
      .catch(() => {
        if (!cancelled) setFailed(true);
      });
    return () => {
      cancelled = true;
    };
  }, [term, isValid]);

  if (!isValid || failed) return null;

  return (
    <div>
      <div className="mb-3 flex flex-wrap items-center justify-between gap-2">
        <div className="flex flex-wrap items-center gap-2">
          <i className="uil uil-shopping-cart-alt text-accent" />
          <h2 className="text-sm font-semibold tracking-wide uppercase text-body">
            Not on the board yet — picks from the web
          </h2>
          <Badge>AI picks · opens Google Shopping</Badge>
        </div>
        <a
          href={shopUrl(term)}
          target="_blank"
          rel="nofollow noopener noreferrer"
          className="inline-flex items-center gap-1 rounded-lg border border-solid border-line bg-surface px-3 py-1.5 text-xs font-medium text-title transition-colors hover:border-accent hover:text-accent"
        >
          <i className="uil uil-google" /> Search Google Shopping for &ldquo;{term}&rdquo;
          <i className="uil uil-external-link-alt" />
        </a>
      </div>

      {!items ? (
        <PicksSkeleton cols="grid-cols-2 sm:grid-cols-3" />
      ) : (
        <PicksGrid items={items} hues={hues} />
      )}

      <p className="mt-2 text-[11px] text-body-light">
        Suggestions generated by AI — prices are rough estimates, check the
        store page. Have a favourite? Suggest it so it lands on the board.
      </p>
    </div>
  );
}
